# -*- coding: utf-8 -*-

# Macro Begin: /home/amcintosh/.FreeCAD/Macro/shelves_007_standard_body.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
import FreeCAD
import PartDesign

group_bodies = App.ActiveDocument.addObject('App::DocumentObjectGroup', 'group_bodies')
#
this_body = group_bodies.newObject('PartDesign::Body','bd_standard')
#
# --- ProfMac --- some magic might help below
#
this_sketch_1=this_body.newObject('Sketcher::SketchObject','sk_standard001')
this_sketch_1.restoreContent(App.ActiveDocument.sk_standard.dumpContent())
this_sketch = App.ActiveDocument.sk_standard
App.activeDocument().bd_standard.Group = [App.activeDocument().sk_standard, App.activeDocument().sk_standard001]
#
# --- ProfMac --- some magic might help above
#
App.ActiveDocument.recompute()
#features_ = [App.ActiveDocument.sk_standard]
#App.ActiveDocument.Footer.removeObjects(features_)
#App.ActiveDocument.bd_standard.addObjects(features_)
this_pad = this_body.newObject("PartDesign::Pad","pd_standard")
this_pad.Profile = this_sketch
this_pad.Length = 10.0
this_pad.setExpression('Length', u'sp_standard.height')
this_pad.Length2 = 99.999800
this_pad.Type = 0
this_pad.UpToFace = None
this_pad.Reversed = 0
this_pad.Midplane = 0
this_pad.Offset = 0.000000
this_pad.recompute()
#
# ----
#
this_pad_extension = this_body.newObject("PartDesign::Pad","pd_extend")
#this_sketch.Support = (this_pad,["Face2"])
this_pad_extension.Profile = this_sketch
this_pad_extension.Length = 10.0
this_pad_extension.setExpression('Length', u'sp_global.elevation')
this_pad_extension.Length2 = 99.999800
this_pad_extension.Type = 0
this_pad_extension.UpToFace = None
this_pad_extension.Reversed = 1
this_pad_extension.Midplane = 0
this_pad_extension.Offset = 0.000000
this_pad_extension.recompute()
#
# ----
#
Gui.activeDocument().activeView().viewIsometric()
Gui.activeDocument().hide("sk_standard002")

# Macro End: /home/amcintosh/.FreeCAD/Macro/shelves_008_standard_body_addendum.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++

