#  --------------------------------------------------------
#  -- Copyright (c) 2020-06-24 by Aubrey McIntosh, PhD   --
#  -- Permission granted for use in educational settings --
#  -- and personal study with this notice left intact.   --
#  --------------------------------------------------------

# -*- coding: utf-8 -*-

# Macro Begin: /home/amcintosh/.FreeCAD/Macro/shelves_010_spacer.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
import FreeCAD
import PartDesignGui
import Sketcher

FreeCAD.Console.PrintMessage("Starting busybox_008_spacer.\n")
part_bodies = App.ActiveDocument.prototypes_of_bodies_1
this_body = part_bodies.newObject("PartDesign::Body","bd_spacer_00" + str(1))

for i in [App.ActiveDocument.sk_spacer_body_000, \
  App.ActiveDocument.sk_spacer_notch_000, App.ActiveDocument.sk_spacer_notch_000,  \
  App.ActiveDocument.sk_dovetail_bottom_000, App.ActiveDocument.sk_dovetail_bottom_000, ]:
 aux_sketch = App.ActiveDocument.copyObject(i)
 this_body.Group += [aux_sketch ,]
 Gui.activeDocument().hide(i.Name)
 Gui.activeDocument().hide(aux_sketch.Name)

#
#
# ----
#
#
this_sketch = App.activeDocument().sk_spacer_body_002
#this_sketch.Support = (App.activeDocument().XZ_Plane, [''])
this_sketch.MapMode = 'FlatFace'
#
this_pad = this_body.newObject("PartDesign::Pad","pd_spacer")
this_pad.Profile = this_sketch
Gui.activeDocument().hide("sk_spacer_body_002")
this_pad.setExpression('Length', u'sp_footer.length + sp_standard.width')
this_pad.Length2 = 99.999800
this_pad.Type = 0
this_pad.UpToFace = None
this_pad.Reversed = 1
this_pad.Midplane = 0
this_pad.Offset = 0.000000
#
this_notch_e = this_body.newObject("PartDesign::Pocket","pk_spacer_joist_notchE")
this_sketch = App.activeDocument().sk_spacer_notch_001
this_notch_e.Profile = this_sketch
this_notch_e.Length = 20.0
this_notch_e.Length = 0.000000
this_notch_e.Length2 = 99.999800
this_notch_e.Type = 'ThroughAll'
#this_notch_e.UpToFace = (App.activeDocument().pk_support_001, ["Face8"])
this_notch_e.Reversed = 0
this_notch_e.Midplane = 0
this_notch_e.Offset = -50.800000
Gui.activeDocument().hide(this_sketch.Name)
Gui.activeDocument().hide(this_pad.Name)
App.ActiveDocument.recompute()
#
this_notch_o = this_body.newObject("PartDesign::Pocket","pk_spacer_joist_notchO")
this_sketch = App.activeDocument().sk_spacer_notch_002
this_sketch.Placement.Base.y += 25.4 * 2.5
this_notch_o.Profile = this_sketch
this_notch_o.Length = 20.0
this_notch_o.Length = 0.000000
this_notch_o.Length2 = 99.999800
this_notch_o.Type = 'ThroughAll'
#this_notch_o.UpToFace = (App.activeDocument().pk_support_002, ["Face8"])
this_notch_o.Reversed = 0
this_notch_o.Midplane = 0
this_notch_o.Offset = -50.800000
Gui.activeDocument().hide(this_sketch.Name)
Gui.activeDocument().hide(this_pad.Name)
App.ActiveDocument.recompute()
#
this_notch_s1 = this_body.newObject("PartDesign::Pocket","pk_spacer_skirt_notch_001")
this_sketch = App.activeDocument().sk_dovetail_bottom_001
this_notch_s1.Profile = this_sketch
this_notch_s1.Length = 20.0
this_notch_s1.Length = 0.000000
this_notch_s1.Length2 = 99.999800
this_notch_s1.Type = 'ThroughAll'
this_notch_s1.Reversed = 1
this_notch_s1.Midplane = 0
this_notch_s1.Offset = -50.800000
Gui.activeDocument().hide(this_sketch.Name)
Gui.activeDocument().hide(this_pad.Name)
App.ActiveDocument.recompute()
#
this_notch_s2 = this_body.newObject("PartDesign::Pocket","pk_spacer_skirt_notch_002")
this_sketch = App.activeDocument().sk_dovetail_bottom_002
aux_rot = App.Rotation( App.Vector(0, 0, 1), 180)
this_sketch.Placement.Rotation = aux_rot.multiply(this_sketch.Placement.Rotation)
this_sketch.Placement.Base.y += float(App.ActiveDocument.sp_footer.get(App.ActiveDocument.sp_footer.getCellFromAlias("length"))) \
  + float(App.ActiveDocument.sp_joist.get(App.ActiveDocument.sp_joist.getCellFromAlias("width")))
this_notch_s2.Profile = this_sketch
this_notch_s2.Length = 20.0
this_notch_s2.Length = 0.000000
this_notch_s2.Length2 = 99.999800
this_notch_s2.Type = 'ThroughAll'
this_notch_s2.Reversed = 0
this_notch_s2.Midplane = 0
this_notch_s2.Offset = -50.800000
Gui.activeDocument().hide(this_sketch.Name)
Gui.activeDocument().hide(this_pad.Name)
App.ActiveDocument.recompute()
#
# ----
#
this_linear = this_body.newObject("PartDesign::LinearPattern","lp_notch_for_joist")
FreeCAD.Console.PrintMessage("Internal name " + this_linear.Name + ".\n")
this_linear.Originals = [this_notch_e, this_notch_o, ]
this_linear.Direction = (App.activeDocument().sk_spacer_notch_002, ["V_Axis"])
this_linear.setExpression('Length', u'sp_footer.length-4 in ')
this_linear.setExpression('Occurrences', u'sp_spacer.spacer_count')
this_linear.Reversed = 0
this_body.Tip = this_linear
Gui.activeDocument().show("lp_notch_for_joist")
Gui.activeDocument().hide("pk_joist_notch")
Gui.activeDocument().show(this_linear.Name)
#

App.ActiveDocument.recompute()
#
#
# ----
#
FreeCAD.Console.PrintMessage("busybox_009_spacer, line 105\n")

this_ch = this_body.newObject("PartDesign::Chamfer","ch_spacer_000")
Gui.ActiveDocument.getObject(this_ch.Name).Transparency=25
this_ch.Base = (this_linear,[ \
  "Edge10", "Edge12", "Edge14", "Edge16", "Edge18", \
  "Edge20", "Edge22", "Edge24", "Edge26", "Edge28", \
  "Edge30", "Edge32", "Edge34", "Edge36", "Edge38", \
  "Edge40", "Edge42", "Edge44", "Edge46", "Edge48", \
  "Edge50", \
  "Edge13", "Edge17", "Edge14", "Edge16", "Edge18", \
  "Edge21", "Edge25", "Edge29", \
  "Edge33", "Edge37",  \
  "Edge41", "Edge45", "Edge49", \
  "Edge53", "Edge55", "Edge57", "Edge59", "Edge61", \
  "Edge63", "Edge65", "Edge67", "Edge69", "Edge71", \
  "Edge73", "Edge75", "Edge77", "Edge79", "Edge81", \
  "Edge83", "Edge85", "Edge87", "Edge89", "Edge91", \
  "Edge54", "Edge62", "Edge70", "Edge78", "Edge86",  \
  "Edge58", "Edge66", "Edge74", "Edge82", "Edge90", \
  ])
this_ch.Size = 1.270000
Gui.activeDocument().show("ch_spacer_000")

