# -*- coding: utf-8 -*-

# Macro Begin: /home/amcintosh/Documents/FreeCAD/Busybox/Macro/busybox_shelf.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
import FreeCAD

App.activeDocument().Tip = App.activeDocument().addObject('App::Part','Wall_')
this_part = App.activeDocument().Tip
ix = 0
for i in [ \
  App.ActiveDocument.lp_support,  \
  App.ActiveDocument.lp_support,  \
  App.ActiveDocument.lp_support,  \
  App.ActiveDocument.lp_support,  \
  App.ActiveDocument.lp_support,  \
  App.ActiveDocument.lp_support,  \
  App.ActiveDocument.lp_support,  \
  ]:
 aux_body = App.ActiveDocument.copyObject(i)
 this_part.Group += [aux_body ,]
 aux_body.Placement.Base.y += ix * 25.4 * 3
 ix += 1

# Macro End: /home/amcintosh/Documents/FreeCAD/Busybox/Macro/busybox_shelf.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
